### ISSUE TITLE
Implement includes support on terms_stats

### ISSUE THREAD

**Issue by doug-patterson** [smartprocure/contexture-elasticsearch#122]
terms_stats should support passing in a list of includes so you can choose what you want out of sum, count, avg, min, etc and have the rest not even get calculated by ES

**Comment by daedalus28** [comment]
Just some notes to help nudge you along: [`avg`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-avg-aggregation.html), [`max`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-max-aggregation.html), [`min`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-min-aggregation.html), [`sum`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-sum-aggregation.html) and [`value_count`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-valuecount-aggregation.html) are all available as metric aggregations with basically the same syntax as [`stats`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-stats-aggregation.html)

With the exception of count/valueCount, the other fields map 1-1 with the agg names. You can use `F.alias` to the aliasing and then just map over `includes` to generate the aggs or use stats if it's missing or empty. The response format for the individual aggs seems to always put the inner value as `value` making easy to iterate over. You can use agg names that are the same as the agg type to make it really easy to map over
