### ISSUE TITLE
Fix Outdated Readme

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture-elasticsearch#146]
Some things I noticed:

- `date` still shows the old props even though @dubiousdavid updated them.
- `dateRageFacet` isn't documented at all

**Comment by daedalus28** [comment]
@dubiousdavid @Akrion FYI - I took care of this in #148 here: https://github.com/smartprocure/contexture-elasticsearch/pull/148/commits/7299f86864b21934f5ce216c43faf4c4ecab263b

**Comment by dubiousdavid** [comment]
Nice!

**Comment by daedalus28** [comment]
Released as part of v1
