### ISSUE TITLE
Improve `toSafeRegex` Performance

### ISSUE THREAD

**Issue by doug-patterson** [smartprocure/contexture-elasticsearch#174]
`toSafeRegex` has some issues that lead to slow queries

 * uses `.*`instead of `.*?` which causes recursive backtracking - it's a known regex engine performance killer
   * lots of articles on the web about this -- here's a recent one: https://javascript.info/regexp-catastrophic-backtracking
 * I see no need for the match on each letter - the elastic regex engine must support case insensitive matches. Will investigate why it was ever done this way, though

**Comment by daedalus28** [comment]
Case insensitive regex is a new feature on es7 - we just added support for it on the tags text type but can use it everywhere.

**Comment by doug-patterson** [comment]
@daedalus28 would you consider boosting performance by ceasing to support typing the words out of order in the facet options filter and a couple other places? I think without that there's really no need for regex matching anywhere in this module

**Comment by doug-patterson** [comment]
Since to my knowledge we have power users who do appreciate the matching power of the current facet options filter I'll focus for now on boosting performance in the regex matches we have rather than on eliminating them entirely (which is what I'd really recommend long-term -- we can still discuss)

**Comment by doug-patterson** [comment]
Update: changes are good to go but I'm WIP updating no fewer that fourteen unit tests

**Comment by doug-patterson** [comment]
I also just realized that the existing `buildRegexQueryForWords` actually doesn't support typing words in any order (unlike F.wordsToRegExp) - try it out on a regex engine like regex101.com with `.*([Cc][Ii][Tt][Yy]).*.*([Oo][Ff]).*`. So I'm more puzzled than i was what the current setup was for. I'll soldier on with my changes but I'll want to make sure I'm not missing some functionality supported by the legacy way of doing it.
