### ISSUE TITLE
Make it so facet can override hasValue if a flag is set

### ISSUE THREAD

**Issue by sadasant** [smartprocure/contexture-elasticsearch#91]
To allow a blank search to be blank.

An alternative is to add a new type.

**Comment by daedalus28** [comment]
I don't fully remember the context for this and the ticket is a bit vague, but I suspect it was about subqueries. I'm pretty sure that this is handled now with native client and server subqueries, so I'm closing this. We can reopen if anyone remembers what this was and it turns out I'm wrong 😅
