### ISSUE TITLE
Change modeMap

### ISSUE THREAD

**Issue by dubiousdavid** [smartprocure/contexture-elasticsearch#94]
Remove concept of modeMap and use analyzed and notAnalyzed instead. Based on discussions for stand-up on 9/18/18.

**Comment by daedalus28** [comment]
#113 gets us most of the way there with it 100% automatic if you provide it the ES mappings (which modern usages should). It maintains backwards compatibility so we don't need to update existing things, but a future breaking release will drop support for the legacy behavior.

**Comment by daedalus28** [comment]
Released as part of v1
